name: 自动签到


on:

  schedule:

    # 北京时间每天8点
    # UTC时间0点
    - cron: '0 0 * * *'


  workflow_dispatch:



jobs:

  sign:


    runs-on: ubuntu-latest


    steps:


    - name: 拉取代码
      uses: actions/checkout@v4



    - name: 安装Python
      uses: actions/setup-python@v5

      with:

        python-version: "3.11"



    - name: 安装依赖

      run: |

        pip install -r requirements.txt



    - name: 执行签到

      env:

        VIP_USER: ${{ secrets.VIP_USER }}

        VIP_PASS: ${{ secrets.VIP_PASS }}

      run: |

        python sign.py
    - name: keep alive action
      uses: efrecon/gh-action-keepalive@main # using the workflow with default settings
