name: 自动签到


on:

  schedule:

    # UTC 17点30分(北京时间 1:30)
    - cron: '30 17 * * *'


  workflow_dispatch:



jobs:

  sign:


    runs-on: ubuntu-latest


    steps:


    - name: 拉取代码
      uses: actions/checkout@v5



    - name: 安装Python
      uses: actions/setup-python@v6

      with:

        python-version: "3.11"



    - name: 安装依赖

      run: |

        pip install -r requirements.txt



    - name: 执行签到

      env:

        VIP_USER: ${{ secrets.VIP_USER }}

        VIP_PASS: ${{ secrets.VIP_PASS }}

      run: |

        python sign.py
  cleanup:


    runs-on: ubuntu-latest


    needs: sign


    permissions:

      actions: write


    steps:


    - name: 清理旧运行记录

      uses: actions/github-script@v8

      with:

        script: |

          const runs = await github.rest.actions.listWorkflowRunsForRepo({

            owner: context.repo.owner,

            repo: context.repo.repo,

            per_page: 100

          });


          const keep = 1;


          const oldRuns = runs.data.workflow_runs.slice(keep);


          for (const run of oldRuns) {

            console.log(
              `删除: ${run.id}`
            );


            await github.rest.actions.deleteWorkflowRun({

              owner: context.repo.owner,

              repo: context.repo.repo,

              run_id: run.id

            });

          }
    - name: keep alive action
      uses: efrecon/gh-action-keepalive@main # using the workflow with default settings
